name: Build OutdoorActivities App for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Or install your package

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Package Application with PyInstaller
      run: |
        pyinstaller --clean weather.spec
        # pyinstaller src/package/showWeatherForecast.py --onefile --windowed # Customize PyInstaller options
    
    #- name: Create ZIP archive
    #  run: Compress-Archive -Path "dist\WeatherBike\*" -DestinationPath "dist\WeatherBike.zip"
    #  shell: powershell
    
    #- name: Zip Archive
    #  run: zip -r WeatherBike.zip dist/WeatherBike/
      
    - name: Upload Artifact Raw
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/WeatherBike/

    #- name: Upload Artifact Zip
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: zip
    #    path: dist/WeatherBike.zip
